import {PGlite} from '@electric-sql/pglite';
import fs from 'node:fs';
import assert from 'node:assert/strict';
import {fileURLToPath} from 'node:url';
const db=new PGlite();
await db.exec(`create role anon;create role authenticated;create schema auth;
  create table auth.users(id uuid primary key);
  create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
  grant usage on schema auth to authenticated,anon;grant execute on function auth.uid() to authenticated,anon;
  insert into auth.users values ('00000000-0000-0000-0000-000000000001'),('00000000-0000-0000-0000-000000000002');`);
await db.exec(fs.readFileSync(fileURLToPath(new URL('./schema.sql',import.meta.url)),'utf8'));
await db.exec(`set role authenticated;set request.jwt.claim.sub='00000000-0000-0000-0000-000000000001';`);
const call=async(p,rev)=>(await db.query('select public.save_ceh_progress($1::jsonb,$2::bigint) result',[JSON.stringify(p),rev])).rows[0].result;
let a=await call({progress:{},stats:{xp:10503}},0);assert.equal(a.ok,true);assert.equal(a.revision,1);
let stale=await call({progress:{},stats:{xp:0}},0);assert.equal(stale.ok,false);assert.equal(stale.payload.stats.xp,10503);
let next=await call({progress:{},stats:{xp:10513}},1);assert.equal(next.revision,2);
await db.exec(`set request.jwt.claim.sub='00000000-0000-0000-0000-000000000002';`);
assert.equal((await db.query('select * from public.ceh_progress')).rows.length,0);
assert.equal((await db.query("update public.ceh_progress set payload='{}' where user_id='00000000-0000-0000-0000-000000000001' returning *")).rows.length,0);
await assert.rejects(db.query("insert into public.ceh_progress(user_id,payload) values ('00000000-0000-0000-0000-000000000001','{\"progress\":{},\"stats\":{}}')"),/row-level security/);
await call({progress:{},stats:{xp:10}},0);
assert.equal((await db.query('select * from public.ceh_progress')).rows.length,1);
await assert.rejects(call({progress:[],stats:{}},1),/ceh_payload_shape/);
await assert.rejects(call({},1),/ceh_payload_shape/);
await assert.rejects(db.query('delete from public.ceh_progress'),/permission denied/);
await db.exec('reset role;set role anon;');
await assert.rejects(db.query('select * from public.ceh_progress'),/permission denied/);
await assert.rejects(call({progress:{},stats:{}},0),/permission denied/);
await db.close();console.log('PASS: schema, revision protection, two-user isolation, anonymous denial, invalid payload denial, deletion denial');
